### ISSUE TITLE
Not finding the uniform distribution

### ISSUE THREAD

**Issue by aolney** [phitterio/phitter-kernel#2]
Using 0.7.1 and trying to get "uniform" from the variety/species column of the `iris` dataset, but it does not consider "uniform" as a possible result:

```python
import pandas as pd

def is_cat(column):
    categorical_dtypes = ['object', 'category', 'bool']
    if column.dtype.name in categorical_dtypes:
        return True
    else:
        return False   

# starts recoding at 0
def convertStringColumnsToNum(data):
    for col in data.columns:
        if(is_cat(data[col])): 
            tmp = pd.Categorical(data[col])
            data[col] = tmp.codes

df = pd.read_csv("https://gist.github.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
convertStringColumnsToNum(df)

import phitter
phi = phitter.PHITTER(data=df['variety'],fit_type="discrete")
phi.fit()
phi.summarize_info()
```

Returns

|   distribution |      sse |                         parameters | chi_square | kolmogorov_smirnov |   |
|---------------:|---------:|-----------------------------------:|-----------:|-------------------:|---|
|        poisson | 0.024705 |                    {'lambda': 1.0} |       True |              False |   |
|       binomial | 0.026655 | {'n': 3, 'p': 0.32885906040268453} |       True |              False |   |
| hypergeometric | 0.032559 |          {'N': 26, 'K': 5, 'n': 5} |       True |              False |   |
|    logarithmic | 0.666558 |      {'p': 0.00010895231352320147} |       None |               True |   |

But the correct answer is uniform, which is not given as a possible result.

```python
phi.plot_histogram_distributions()
```

![newplot](https://github.com/user-attachments/assets/08149569-9876-42c9-8a43-71292a3b5e68)

**Comment by sebastianherreramonterrosa** [comment]
Hi @aolney, the case where the critical value is equal to zero was not considered earlier, but it has already been resolved. Please update the Phitter package and try again.
<img width="450" alt="image" src="https://github.com/user-attachments/assets/fefa531a-8826-4b19-accb-6b9bf1b626a8">

<img width="464" alt="image" src="https://github.com/user-attachments/assets/5e975b58-5eeb-4479-8876-6e6417a0b3fc">

**Comment by aolney** [comment]
Awesome, problem solved :tada:
